"""added name and contact

Revision ID: 74163fe4f8d2
Revises: 81f7b7ccf483
Create Date: 2022-05-01 10:38:56.562973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74163fe4f8d2'
down_revision = '81f7b7ccf483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('contact', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'contact')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
