"""Added user.is_banned

Revision ID: 9fcc995b9609
Revises: b8279f8256ca
Create Date: 2022-04-14 01:34:10.408608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fcc995b9609'
down_revision = 'b8279f8256ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_banned')
    # ### end Alembic commands ###
