"""Added user.number

Revision ID: b8279f8256ca
Revises: 5aaf488c8a77
Create Date: 2022-04-13 22:42:03.030445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8279f8256ca'
down_revision = '5aaf488c8a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'number')
    # ### end Alembic commands ###
