"""Added column for notifications

Revision ID: fdbe0ba85feb
Revises: 85a371f16232
Create Date: 2022-04-09 20:31:43.763781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fdbe0ba85feb'
down_revision = '85a371f16232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager', sa.Column('unread_msgs', postgresql.ARRAY(sa.String(length=255)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manager', 'unread_msgs')
    # ### end Alembic commands ###
